/*
 * This file is part of OpenTTD.
 * OpenTTD is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, version 2.
 * OpenTTD is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with OpenTTD. If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file airtypes.h
 * All the airtype-specific information is stored here.
 */

#ifndef AIRTYPES_H
#define AIRTYPES_H

#include "air.h"

#include "table/sprites.h"
#include "table/strings.h"

/**
 * Global AirType definition
 */
static const AirTypeInfo _original_airtypes[] = {
	/** Gravel */
	{ // Main Sprites
		{
			{
				SPR_AIRPORT_TYPE_GRAVEL + 22,
				SPR_AIRPORT_TYPE_GRAVEL + 23,
				SPR_AIRPORT_TYPE_GRAVEL + 24,
				SPR_AIRPORT_TYPE_GRAVEL + 25,
				SPR_AIRPORT_TYPE_GRAVEL + 26,
				SPR_AIRPORT_TYPE_GRAVEL + 22,
				SPR_AIRPORT_TYPE_GRAVEL + 22,
				SPR_AIRPORT_TYPE_GRAVEL + 22,
				SPR_AIRPORT_TYPE_GRAVEL + 22,
				SPR_AIRPORT_TYPE_GRAVEL + 22,
				SPR_AIRPORT_TYPE_GRAVEL + 22,
				SPR_AIRPORT_TYPE_GRAVEL + 22,
				SPR_AIRPORT_TYPE_GRAVEL + 22,
				SPR_AIRPORT_TYPE_GRAVEL + 22,
				SPR_AIRPORT_TYPE_GRAVEL + 22,
				SPR_AIRPORT_TYPE_GRAVEL + 22,
				SPR_AIRPORT_TYPE_GRAVEL + 22,
				SPR_AIRPORT_TYPE_GRAVEL + 22,
				SPR_AIRPORT_TYPE_GRAVEL + 22,
				SPR_AIRPORT_TYPE_GRAVEL + 22,
			},
			{
				{
					{ SPR_AIRPORT_TYPE_GRAVEL + 89, SPR_AIRPORT_TYPE_GRAVEL + 90,
						SPR_AIRPORT_TYPE_GRAVEL + 91, SPR_AIRPORT_TYPE_GRAVEL+ 92
					},
					{ SPR_AIRPORT_TYPE_GRAVEL + 93, SPR_AIRPORT_TYPE_GRAVEL + 94,
						SPR_AIRPORT_TYPE_GRAVEL + 95, SPR_AIRPORT_TYPE_GRAVEL + 96
					},
					{ SPR_AIRPORT_TYPE_GRAVEL + 97, SPR_AIRPORT_TYPE_GRAVEL + 98,
						SPR_AIRPORT_TYPE_GRAVEL + 99, SPR_AIRPORT_TYPE_GRAVEL + 100
					},
					{ SPR_AIRPORT_TYPE_GRAVEL + 101, SPR_AIRPORT_TYPE_GRAVEL + 102,
						SPR_AIRPORT_TYPE_GRAVEL + 103, SPR_AIRPORT_TYPE_GRAVEL + 104
					},
					{ SPR_AIRPORT_TYPE_GRAVEL + 105, SPR_AIRPORT_TYPE_GRAVEL + 106,
						SPR_AIRPORT_TYPE_GRAVEL + 107, SPR_AIRPORT_TYPE_GRAVEL + 108
					}
				},
				{
					{ SPR_AIRPORT_TYPE_GRAVEL + 109, SPR_AIRPORT_TYPE_GRAVEL + 110,
						SPR_AIRPORT_TYPE_GRAVEL + 111, SPR_AIRPORT_TYPE_GRAVEL + 112
					},
					{ SPR_AIRPORT_TYPE_GRAVEL + 113, SPR_AIRPORT_TYPE_GRAVEL + 114,
						SPR_AIRPORT_TYPE_GRAVEL + 115, SPR_AIRPORT_TYPE_GRAVEL + 116
					},
					{ SPR_AIRPORT_TYPE_GRAVEL + 117, SPR_AIRPORT_TYPE_GRAVEL + 118,
						SPR_AIRPORT_TYPE_GRAVEL + 119, SPR_AIRPORT_TYPE_GRAVEL + 120
					},
					{ SPR_AIRPORT_TYPE_GRAVEL + 121, SPR_AIRPORT_TYPE_GRAVEL + 122,
						SPR_AIRPORT_TYPE_GRAVEL + 123, SPR_AIRPORT_TYPE_GRAVEL + 124
					},
					{ SPR_AIRPORT_TYPE_GRAVEL + 125, SPR_AIRPORT_TYPE_GRAVEL + 126,
						SPR_AIRPORT_TYPE_GRAVEL + 127, SPR_AIRPORT_TYPE_GRAVEL + 128
					}
				}
			},
			{
				{ SPR_AIRFIELD_WIND_1, SPR_AIRFIELD_WIND_2, SPR_AIRFIELD_WIND_3, SPR_AIRFIELD_WIND_4 }, // wind
				{ SPR_AIRFIELD_WIND_1, SPR_AIRFIELD_WIND_2, SPR_AIRFIELD_WIND_3, SPR_AIRFIELD_WIND_4 },
				{ SPR_AIRFIELD_WIND_1, SPR_AIRFIELD_WIND_2, SPR_AIRFIELD_WIND_3, SPR_AIRFIELD_WIND_4 },
				{ SPR_AIRFIELD_WIND_1, SPR_AIRFIELD_WIND_2, SPR_AIRFIELD_WIND_3, SPR_AIRFIELD_WIND_4 }
			},
			{ SPR_AIRPORT_RADAR_1, SPR_AIRPORT_RADAR_2, SPR_AIRPORT_RADAR_3, SPR_AIRPORT_RADAR_4, // radar
				SPR_AIRPORT_RADAR_5, SPR_AIRPORT_RADAR_6, SPR_AIRPORT_RADAR_7, SPR_AIRPORT_RADAR_8,
				SPR_AIRPORT_RADAR_9, SPR_AIRPORT_RADAR_A, SPR_AIRPORT_RADAR_B, SPR_AIRPORT_RADAR_C
			},
			{
				{ SPR_AIRPORT_TYPE_GRAVEL + 73, SPR_AIRPORT_TYPE_GRAVEL + 74, // transmitter
					SPR_AIRPORT_TYPE_GRAVEL + 75, SPR_AIRPORT_TYPE_GRAVEL + 76
				},
				{ SPR_AIRPORT_TYPE_GRAVEL + 77, SPR_AIRPORT_TYPE_GRAVEL + 78,
					SPR_AIRPORT_TYPE_GRAVEL + 79, SPR_AIRPORT_TYPE_GRAVEL + 80
				},
				{ SPR_AIRPORT_TYPE_GRAVEL + 81, SPR_AIRPORT_TYPE_GRAVEL + 82, // snowed transmitter
					SPR_AIRPORT_TYPE_GRAVEL + 83, SPR_AIRPORT_TYPE_GRAVEL + 84
				},
				{ SPR_AIRPORT_TYPE_GRAVEL + 85, SPR_AIRPORT_TYPE_GRAVEL + 86,
					SPR_AIRPORT_TYPE_GRAVEL + 87, SPR_AIRPORT_TYPE_GRAVEL + 88
				}
			},
			{ SPR_AIRPORT_TYPE_GRAVEL + 27, SPR_AIRPORT_TYPE_GRAVEL + 28, SPR_AIRPORT_TYPE_GRAVEL +29, // runways
				SPR_AIRPORT_TYPE_GRAVEL + 30, SPR_AIRPORT_TYPE_GRAVEL + 31, SPR_AIRPORT_TYPE_GRAVEL + 32,
				SPR_AIRPORT_TYPE_GRAVEL +33, SPR_AIRPORT_TYPE_GRAVEL +34, SPR_AIRPORT_TYPE_GRAVEL +35,
				SPR_AIRPORT_TYPE_GRAVEL + 36, SPR_AIRPORT_TYPE_GRAVEL + 37, SPR_AIRPORT_TYPE_GRAVEL + 38,
				SPR_AIRPORT_TYPE_GRAVEL + 39, SPR_AIRPORT_TYPE_GRAVEL + 40, SPR_AIRPORT_TYPE_GRAVEL + 41,
				SPR_AIRPORT_TYPE_GRAVEL + 42, SPR_AIRPORT_TYPE_GRAVEL + 43, SPR_AIRPORT_TYPE_GRAVEL + 44,
				SPR_AIRPORT_TYPE_GRAVEL + 45, SPR_AIRPORT_TYPE_GRAVEL + 46, SPR_AIRPORT_TYPE_GRAVEL + 47,
				SPR_AIRPORT_TYPE_GRAVEL + 48, SPR_AIRPORT_TYPE_GRAVEL + 49, SPR_AIRPORT_TYPE_GRAVEL + 50
			},
			{ SPR_AIRPORT_TYPE_GRAVEL + 63, SPR_AIRPORT_TYPE_GRAVEL + 64, // plane apron, helipad
				SPR_AIRPORT_TYPE_GRAVEL + 65, SPR_AIRPORT_TYPE_GRAVEL + 66, SPR_AIRPORT_TYPE_GRAVEL + 67, // 4 heliport rotations + 4 snow heliports
				SPR_AIRPORT_TYPE_GRAVEL + 68, SPR_AIRPORT_TYPE_GRAVEL + 69, SPR_AIRPORT_TYPE_GRAVEL + 70,
				SPR_AIRPORT_TYPE_GRAVEL + 71, SPR_AIRPORT_TYPE_GRAVEL + 72
			},
			{ SPR_AIRPORT_TYPE_GRAVEL + 51, SPR_AIRPORT_TYPE_GRAVEL + 52, SPR_AIRPORT_TYPE_GRAVEL + 53,
				SPR_AIRPORT_TYPE_GRAVEL + 54, SPR_AIRPORT_TYPE_GRAVEL + 55, SPR_AIRPORT_TYPE_GRAVEL + 56,
				SPR_AIRPORT_TYPE_GRAVEL + 57, SPR_AIRPORT_TYPE_GRAVEL + 58, SPR_AIRPORT_TYPE_GRAVEL + 59,
				SPR_AIRPORT_TYPE_GRAVEL + 60, SPR_AIRPORT_TYPE_GRAVEL + 61, SPR_AIRPORT_TYPE_GRAVEL + 62
			}
		},

		/* GUI sprites */
		{	SPR_AIRPORT_TYPE_GRAVEL,     // add tile to airport
			SPR_AIRPORT_TYPE_GRAVEL + 1, // build track tile
			SPR_AIRPORT_TYPE_GRAVEL + 2, // change air type
			SPR_AIRPORT_TYPE_GRAVEL + 3, // define runway
			SPR_AIRPORT_TYPE_GRAVEL + 4, // apron
			SPR_AIRPORT_TYPE_GRAVEL + 5, // helipad
			SPR_AIRPORT_TYPE_GRAVEL + 6, // heliport
			SPR_AIRPORT_TYPE_GRAVEL + 7, // hangar
			SPR_AIRPORT_TYPE_GRAVEL + 8, // build predefined
			SPR_AIRPORT_TYPE_GRAVEL + 9, // copy
			SPR_AIRPORT_TYPE_GRAVEL + 10
		},

		/* cursor sprites */
		{	SPR_AIRPORT_TYPE_GRAVEL + 11,
			SPR_AIRPORT_TYPE_GRAVEL + 12,
			SPR_AIRPORT_TYPE_GRAVEL + 13,
			SPR_AIRPORT_TYPE_GRAVEL + 14,
			SPR_AIRPORT_TYPE_GRAVEL + 15,
			SPR_AIRPORT_TYPE_GRAVEL + 16,
			SPR_AIRPORT_TYPE_GRAVEL + 17,
			SPR_AIRPORT_TYPE_GRAVEL + 18,
			SPR_AIRPORT_TYPE_GRAVEL + 19,
			SPR_AIRPORT_TYPE_GRAVEL + 20,
			SPR_AIRPORT_TYPE_GRAVEL + 21
		},

		/* strings */
		{
			STR_AIRTYPE_NAME_GRAVEL,
			STR_TOOLBAR_AIRPORT_GRAVEL_CONSTRUCTION_CAPTION,
			STR_TOOLBAR_AIRPORT_GRAVEL_MENU_TEXT,
			STR_REPLACE_AIRCRAFT_GRAVEL_VEHICLES,
		},

		/* Offset of snow tiles */
		SPR_RAIL_SNOW_OFFSET,

		/* Compatible airtypes */
		AIRTYPES_GRAVEL | AIRTYPES_ASPHALT | AIRTYPES_YELLOW,

		/* fallback_airtype */
		0,

		/* cost multiplier */
		1,

		/* maintenance cost multiplier */
		1,

		/* max speed */
		40,

		/* Gravel type label. */
		AIRTYPE_LABEL_GRAVEL,

		/* alternate labels */
		AirTypeLabelList(),

		/* map colour */
		0x0A,

		/* introduction date */
		CalTime::INVALID_DATE,

		/* airtypes required for this to be introduced */
		AIRTYPES_NONE,

		/* introduction air types */
		AIRTYPES_GRAVEL,

		/* sort order */
		0 << 4 | 7,

		{ nullptr },
		{ nullptr },

		/* Catchment. */
		3,

		/* Max number of runways. */
		2,

		/* Min runway length in tiles. */
		4,

		/* Base noise level. */
		0,

		/* Runway noise level. */
		1,

		/* Heliport availability. */
		false,

		/* Build on water. */
		false,
	},

	/** Asphalt */
	{ // Main Sprites
		{
			{
				SPR_AIRPORT_TYPE_ASPHALT + 22,
				SPR_AIRPORT_TYPE_ASPHALT + 23,
				SPR_AIRPORT_TYPE_ASPHALT + 24,
				SPR_AIRPORT_TYPE_ASPHALT + 25,
				SPR_AIRPORT_TYPE_ASPHALT + 26,
				SPR_AIRPORT_TYPE_ASPHALT + 22,
				SPR_AIRPORT_TYPE_ASPHALT + 22,
				SPR_AIRPORT_TYPE_ASPHALT + 22,
				SPR_AIRPORT_TYPE_ASPHALT + 22,
				SPR_AIRPORT_TYPE_ASPHALT + 22,
				SPR_AIRPORT_TYPE_ASPHALT + 22,
				SPR_AIRPORT_TYPE_ASPHALT + 22,
				SPR_AIRPORT_TYPE_ASPHALT + 22,
				SPR_AIRPORT_TYPE_ASPHALT + 22,
				SPR_AIRPORT_TYPE_ASPHALT + 22,
				SPR_AIRPORT_TYPE_ASPHALT + 22,
				SPR_AIRPORT_TYPE_ASPHALT + 22,
				SPR_AIRPORT_TYPE_ASPHALT + 22,
				SPR_AIRPORT_TYPE_ASPHALT + 22,
				SPR_AIRPORT_TYPE_ASPHALT + 22,
			},
			{
				{
					{ SPR_AIRPORT_TYPE_ASPHALT + 89, SPR_AIRPORT_TYPE_ASPHALT + 90,
						SPR_AIRPORT_TYPE_ASPHALT + 91, SPR_AIRPORT_TYPE_ASPHALT+ 92
					},
					{ SPR_AIRPORT_TYPE_ASPHALT + 93, SPR_AIRPORT_TYPE_ASPHALT + 94,
						SPR_AIRPORT_TYPE_ASPHALT + 95, SPR_AIRPORT_TYPE_ASPHALT + 96
					},
					{ SPR_AIRPORT_TYPE_ASPHALT + 97, SPR_AIRPORT_TYPE_ASPHALT + 98,
						SPR_AIRPORT_TYPE_ASPHALT + 99, SPR_AIRPORT_TYPE_ASPHALT + 100
					},
					{ SPR_AIRPORT_TYPE_ASPHALT + 101, SPR_AIRPORT_TYPE_ASPHALT + 102,
						SPR_AIRPORT_TYPE_ASPHALT + 103, SPR_AIRPORT_TYPE_ASPHALT + 104
					},
					{ SPR_AIRPORT_TYPE_ASPHALT + 105, SPR_AIRPORT_TYPE_ASPHALT + 106,
						SPR_AIRPORT_TYPE_ASPHALT + 107, SPR_AIRPORT_TYPE_ASPHALT + 108
					}
				},
				{
					{ SPR_AIRPORT_TYPE_ASPHALT + 109, SPR_AIRPORT_TYPE_ASPHALT + 110,
						SPR_AIRPORT_TYPE_ASPHALT + 111, SPR_AIRPORT_TYPE_ASPHALT + 112
					},
					{ SPR_AIRPORT_TYPE_ASPHALT + 113, SPR_AIRPORT_TYPE_ASPHALT + 114,
						SPR_AIRPORT_TYPE_ASPHALT + 115, SPR_AIRPORT_TYPE_ASPHALT + 116
					},
					{ SPR_AIRPORT_TYPE_ASPHALT + 117, SPR_AIRPORT_TYPE_ASPHALT + 118,
						SPR_AIRPORT_TYPE_ASPHALT + 119, SPR_AIRPORT_TYPE_ASPHALT + 120
					},
					{ SPR_AIRPORT_TYPE_ASPHALT + 121, SPR_AIRPORT_TYPE_ASPHALT + 122,
						SPR_AIRPORT_TYPE_ASPHALT + 123, SPR_AIRPORT_TYPE_ASPHALT + 124
					},
					{ SPR_AIRPORT_TYPE_ASPHALT + 125, SPR_AIRPORT_TYPE_ASPHALT + 126,
						SPR_AIRPORT_TYPE_ASPHALT + 127, SPR_AIRPORT_TYPE_ASPHALT + 128
					}
				}
			},
			{
				{ SPR_AIRFIELD_WIND_1, SPR_AIRFIELD_WIND_2, SPR_AIRFIELD_WIND_3, SPR_AIRFIELD_WIND_4 }, // wind
				{ SPR_AIRFIELD_WIND_1, SPR_AIRFIELD_WIND_2, SPR_AIRFIELD_WIND_3, SPR_AIRFIELD_WIND_4 },
				{ SPR_AIRFIELD_WIND_1, SPR_AIRFIELD_WIND_2, SPR_AIRFIELD_WIND_3, SPR_AIRFIELD_WIND_4 },
				{ SPR_AIRFIELD_WIND_1, SPR_AIRFIELD_WIND_2, SPR_AIRFIELD_WIND_3, SPR_AIRFIELD_WIND_4 }
			},
			{ SPR_AIRPORT_RADAR_1, SPR_AIRPORT_RADAR_2, SPR_AIRPORT_RADAR_3, SPR_AIRPORT_RADAR_4, // radar
				SPR_AIRPORT_RADAR_5, SPR_AIRPORT_RADAR_6, SPR_AIRPORT_RADAR_7, SPR_AIRPORT_RADAR_8,
				SPR_AIRPORT_RADAR_9, SPR_AIRPORT_RADAR_A, SPR_AIRPORT_RADAR_B, SPR_AIRPORT_RADAR_C
			},
			{
				{ SPR_AIRPORT_TYPE_ASPHALT + 73, SPR_AIRPORT_TYPE_ASPHALT + 74, // transmitter
					SPR_AIRPORT_TYPE_ASPHALT + 75, SPR_AIRPORT_TYPE_ASPHALT + 76
				},
				{ SPR_AIRPORT_TYPE_ASPHALT + 77, SPR_AIRPORT_TYPE_ASPHALT + 78,
					SPR_AIRPORT_TYPE_ASPHALT + 79, SPR_AIRPORT_TYPE_ASPHALT + 80
				},
				{ SPR_AIRPORT_TYPE_ASPHALT + 81, SPR_AIRPORT_TYPE_ASPHALT + 82, // snowed transmitter
					SPR_AIRPORT_TYPE_ASPHALT + 83, SPR_AIRPORT_TYPE_ASPHALT + 84
				},
				{ SPR_AIRPORT_TYPE_ASPHALT + 85, SPR_AIRPORT_TYPE_ASPHALT + 86,
					SPR_AIRPORT_TYPE_ASPHALT + 87, SPR_AIRPORT_TYPE_ASPHALT + 88
				}
			},
			{ SPR_AIRPORT_TYPE_ASPHALT + 27, SPR_AIRPORT_TYPE_ASPHALT + 28, SPR_AIRPORT_TYPE_ASPHALT +29, // runways
					SPR_AIRPORT_TYPE_ASPHALT + 30, SPR_AIRPORT_TYPE_ASPHALT + 31, SPR_AIRPORT_TYPE_ASPHALT + 32,
					SPR_AIRPORT_TYPE_ASPHALT +33, SPR_AIRPORT_TYPE_ASPHALT +34, SPR_AIRPORT_TYPE_ASPHALT +35,
					SPR_AIRPORT_TYPE_ASPHALT + 36, SPR_AIRPORT_TYPE_ASPHALT + 37, SPR_AIRPORT_TYPE_ASPHALT + 38,
					SPR_AIRPORT_TYPE_ASPHALT + 39, SPR_AIRPORT_TYPE_ASPHALT + 40, SPR_AIRPORT_TYPE_ASPHALT + 41,
					SPR_AIRPORT_TYPE_ASPHALT + 42, SPR_AIRPORT_TYPE_ASPHALT + 43, SPR_AIRPORT_TYPE_ASPHALT + 44,
					SPR_AIRPORT_TYPE_ASPHALT + 45, SPR_AIRPORT_TYPE_ASPHALT + 46, SPR_AIRPORT_TYPE_ASPHALT + 47,
					SPR_AIRPORT_TYPE_ASPHALT + 48, SPR_AIRPORT_TYPE_ASPHALT + 49, SPR_AIRPORT_TYPE_ASPHALT + 50
			},
			{ SPR_AIRPORT_TYPE_ASPHALT + 63, SPR_AIRPORT_TYPE_ASPHALT + 64, // plane apron, helipad
				SPR_AIRPORT_TYPE_ASPHALT + 65, SPR_AIRPORT_TYPE_ASPHALT + 66, SPR_AIRPORT_TYPE_ASPHALT + 67, // 4 heliport rotations + 4 snow heliports
				SPR_AIRPORT_TYPE_ASPHALT + 68, SPR_AIRPORT_TYPE_ASPHALT + 69, SPR_AIRPORT_TYPE_ASPHALT + 70,
				SPR_AIRPORT_TYPE_ASPHALT + 71, SPR_AIRPORT_TYPE_ASPHALT + 72
			},
			{ SPR_AIRPORT_TYPE_ASPHALT + 51, SPR_AIRPORT_TYPE_ASPHALT + 52, SPR_AIRPORT_TYPE_ASPHALT + 53,
				SPR_AIRPORT_TYPE_ASPHALT + 54, SPR_AIRPORT_TYPE_ASPHALT + 55, SPR_AIRPORT_TYPE_ASPHALT + 56,
				SPR_AIRPORT_TYPE_ASPHALT + 57, SPR_AIRPORT_TYPE_ASPHALT + 58, SPR_AIRPORT_TYPE_ASPHALT + 59,
				SPR_AIRPORT_TYPE_ASPHALT + 60, SPR_AIRPORT_TYPE_ASPHALT + 61, SPR_AIRPORT_TYPE_ASPHALT + 62
			}
		},

		/* GUI sprites */
		{	SPR_AIRPORT_TYPE_ASPHALT,     // add tile to airport
			SPR_AIRPORT_TYPE_ASPHALT + 1, // build track tile
			SPR_AIRPORT_TYPE_ASPHALT + 2, // change air type
			SPR_AIRPORT_TYPE_ASPHALT + 3, // define runway
			SPR_AIRPORT_TYPE_ASPHALT + 4, // apron
			SPR_AIRPORT_TYPE_ASPHALT + 5, // helipad
			SPR_AIRPORT_TYPE_ASPHALT + 6, // heliport
			SPR_AIRPORT_TYPE_ASPHALT + 7, // hangar
			SPR_AIRPORT_TYPE_ASPHALT + 8, // build predefined
			SPR_AIRPORT_TYPE_ASPHALT + 9, // copy
			SPR_AIRPORT_TYPE_ASPHALT + 10
		},

		/* cursor sprites */
		{	SPR_AIRPORT_TYPE_ASPHALT + 11,
			SPR_AIRPORT_TYPE_ASPHALT + 12,
			SPR_AIRPORT_TYPE_ASPHALT + 13,
			SPR_AIRPORT_TYPE_ASPHALT + 14,
			SPR_AIRPORT_TYPE_ASPHALT + 15,
			SPR_AIRPORT_TYPE_ASPHALT + 16,
			SPR_AIRPORT_TYPE_ASPHALT + 17,
			SPR_AIRPORT_TYPE_ASPHALT + 18,
			SPR_AIRPORT_TYPE_ASPHALT + 19,
			SPR_AIRPORT_TYPE_ASPHALT + 20,
			SPR_AIRPORT_TYPE_ASPHALT + 21
		},

		/* strings */
		{
			STR_AIRTYPE_NAME_ASPHALT,
			STR_TOOLBAR_AIRPORT_ASPHALT_CONSTRUCTION_CAPTION,
			STR_TOOLBAR_AIRPORT_ASPHALT_CONSTRUCTION_CAPTION,
			STR_REPLACE_AIRCRAFT_ASPHALT_VEHICLES,
		},

		/* Offset of snow tiles */
		SPR_RAIL_SNOW_OFFSET,

		/* Compatible airtypes */
		AIRTYPES_ASPHALT | AIRTYPES_YELLOW | AIRTYPES_DARK,

		/* fallback_airtype */
		0,

		/* cost multiplier */
		8,

		/* maintenance cost multiplier */
		8,

		/* max speed */
		80,

		/* Gravel type label. */
		AIRTYPE_LABEL_ASPHALT,

		/* alternate labels */
		AirTypeLabelList(),

		/* map colour */
		0x0A,

		/* introduction date */
		CalTime::INVALID_DATE,

		/* airtypes required for this to be introduced */
		AIRTYPES_NONE,

		/* introduction air types */
		AIRTYPES_ASPHALT | AIRTYPES_DARK | AIRTYPES_YELLOW,

		/* sort order */
		1 << 4 | 7,

		{ nullptr },
		{ nullptr },

		/* Catchment. */
		8,

		/* Max number of runways. */
		4,

		/* Min runway length in tiles. */
		5,

		/* Base noise level. */
		1,

		/* Runway noise level. */
		3,

		/* Heliport availability. */
		true,

		/* Build on water. */
		false,
	},

	/** Water */
	{ // Main Sprites
		{
			{
				SPR_AIRPORT_TYPE_WATER + 22,
				SPR_AIRPORT_TYPE_WATER + 23,
				SPR_AIRPORT_TYPE_WATER + 24,
				SPR_AIRPORT_TYPE_WATER + 25,
				SPR_AIRPORT_TYPE_WATER + 26,
				SPR_AIRPORT_TYPE_WATER + 22,
				SPR_AIRPORT_TYPE_WATER + 22,
				SPR_AIRPORT_TYPE_WATER + 22,
				SPR_AIRPORT_TYPE_WATER + 22,
				SPR_AIRPORT_TYPE_WATER + 22,
				SPR_AIRPORT_TYPE_WATER + 22,
				SPR_AIRPORT_TYPE_WATER + 22,
				SPR_AIRPORT_TYPE_WATER + 22,
				SPR_AIRPORT_TYPE_WATER + 22,
				SPR_AIRPORT_TYPE_WATER + 22,
				SPR_AIRPORT_TYPE_WATER + 22,
				SPR_AIRPORT_TYPE_WATER + 22,
				SPR_AIRPORT_TYPE_WATER + 22,
				SPR_AIRPORT_TYPE_WATER + 22,
				SPR_AIRPORT_TYPE_WATER + 22,
			},
			{
				{
					{ SPR_AIRPORT_TYPE_WATER + 89, SPR_AIRPORT_TYPE_WATER + 90,
						SPR_AIRPORT_TYPE_WATER + 91, SPR_AIRPORT_TYPE_WATER+ 92
					},
					{ SPR_AIRPORT_TYPE_WATER + 93, SPR_AIRPORT_TYPE_WATER + 94,
						SPR_AIRPORT_TYPE_WATER + 95, SPR_AIRPORT_TYPE_WATER + 96
					},
					{ SPR_AIRPORT_TYPE_WATER + 97, SPR_AIRPORT_TYPE_WATER + 98,
						SPR_AIRPORT_TYPE_WATER + 99, SPR_AIRPORT_TYPE_WATER + 100
					},
					{ SPR_AIRPORT_TYPE_WATER + 101, SPR_AIRPORT_TYPE_WATER + 102,
						SPR_AIRPORT_TYPE_WATER + 103, SPR_AIRPORT_TYPE_WATER + 104
					},
					{ SPR_AIRPORT_TYPE_WATER + 105, SPR_AIRPORT_TYPE_WATER + 106,
						SPR_AIRPORT_TYPE_WATER + 107, SPR_AIRPORT_TYPE_WATER + 108
					}
				},
				{
					{ SPR_AIRPORT_TYPE_WATER + 109, SPR_AIRPORT_TYPE_WATER + 110,
						SPR_AIRPORT_TYPE_WATER + 111, SPR_AIRPORT_TYPE_WATER + 112
					},
					{ SPR_AIRPORT_TYPE_WATER + 113, SPR_AIRPORT_TYPE_WATER + 114,
						SPR_AIRPORT_TYPE_WATER + 115, SPR_AIRPORT_TYPE_WATER + 116
					},
					{ SPR_AIRPORT_TYPE_WATER + 117, SPR_AIRPORT_TYPE_WATER + 118,
						SPR_AIRPORT_TYPE_WATER + 119, SPR_AIRPORT_TYPE_WATER + 120
					},
					{ SPR_AIRPORT_TYPE_WATER + 121, SPR_AIRPORT_TYPE_WATER + 122,
						SPR_AIRPORT_TYPE_WATER + 123, SPR_AIRPORT_TYPE_WATER + 124
					},
					{ SPR_AIRPORT_TYPE_WATER + 125, SPR_AIRPORT_TYPE_WATER + 126,
						SPR_AIRPORT_TYPE_WATER + 127, SPR_AIRPORT_TYPE_WATER + 128
					}
				}
			},
			{
				{ SPR_AIRFIELD_WIND_1, SPR_AIRFIELD_WIND_2, SPR_AIRFIELD_WIND_3, SPR_AIRFIELD_WIND_4 }, // wind
				{ SPR_AIRFIELD_WIND_1, SPR_AIRFIELD_WIND_2, SPR_AIRFIELD_WIND_3, SPR_AIRFIELD_WIND_4 },
				{ SPR_AIRFIELD_WIND_1, SPR_AIRFIELD_WIND_2, SPR_AIRFIELD_WIND_3, SPR_AIRFIELD_WIND_4 },
				{ SPR_AIRFIELD_WIND_1, SPR_AIRFIELD_WIND_2, SPR_AIRFIELD_WIND_3, SPR_AIRFIELD_WIND_4 }
			},
			{ SPR_AIRPORT_RADAR_1, SPR_AIRPORT_RADAR_2, SPR_AIRPORT_RADAR_3, SPR_AIRPORT_RADAR_4, // radar
				SPR_AIRPORT_RADAR_5, SPR_AIRPORT_RADAR_6, SPR_AIRPORT_RADAR_7, SPR_AIRPORT_RADAR_8,
				SPR_AIRPORT_RADAR_9, SPR_AIRPORT_RADAR_A, SPR_AIRPORT_RADAR_B, SPR_AIRPORT_RADAR_C
			},
			{
				{ SPR_AIRPORT_TYPE_WATER + 73, SPR_AIRPORT_TYPE_WATER + 74, // transmitter
					SPR_AIRPORT_TYPE_WATER + 75, SPR_AIRPORT_TYPE_WATER + 76
				},
				{ SPR_AIRPORT_TYPE_WATER + 77, SPR_AIRPORT_TYPE_WATER + 78,
					SPR_AIRPORT_TYPE_WATER + 79, SPR_AIRPORT_TYPE_WATER + 80
				},
				{ SPR_AIRPORT_TYPE_WATER + 81, SPR_AIRPORT_TYPE_WATER + 82, // snowed transmitter
					SPR_AIRPORT_TYPE_WATER + 83, SPR_AIRPORT_TYPE_WATER + 84
				},
				{ SPR_AIRPORT_TYPE_WATER + 85, SPR_AIRPORT_TYPE_WATER + 86,
					SPR_AIRPORT_TYPE_WATER + 87, SPR_AIRPORT_TYPE_WATER + 88
				}
			},
			{ SPR_AIRPORT_TYPE_WATER + 27, SPR_AIRPORT_TYPE_WATER + 28, SPR_AIRPORT_TYPE_WATER +29, // runways
				SPR_AIRPORT_TYPE_WATER + 30, SPR_AIRPORT_TYPE_WATER + 31, SPR_AIRPORT_TYPE_WATER + 32,
				SPR_AIRPORT_TYPE_WATER +33, SPR_AIRPORT_TYPE_WATER +34, SPR_AIRPORT_TYPE_WATER +35,
				SPR_AIRPORT_TYPE_WATER + 36, SPR_AIRPORT_TYPE_WATER + 37, SPR_AIRPORT_TYPE_WATER + 38,
				SPR_AIRPORT_TYPE_WATER + 39, SPR_AIRPORT_TYPE_WATER + 40, SPR_AIRPORT_TYPE_WATER + 41,
				SPR_AIRPORT_TYPE_WATER + 42, SPR_AIRPORT_TYPE_WATER + 43, SPR_AIRPORT_TYPE_WATER + 44,
				SPR_AIRPORT_TYPE_WATER + 45, SPR_AIRPORT_TYPE_WATER + 46, SPR_AIRPORT_TYPE_WATER + 47,
				SPR_AIRPORT_TYPE_WATER + 48, SPR_AIRPORT_TYPE_WATER + 49, SPR_AIRPORT_TYPE_WATER + 50
			},
			{ SPR_AIRPORT_TYPE_WATER + 63, SPR_AIRPORT_TYPE_WATER + 64, // plane apron, helipad
				SPR_AIRPORT_TYPE_WATER + 65, SPR_AIRPORT_TYPE_WATER + 66, SPR_AIRPORT_TYPE_WATER + 67, // 4 heliport rotations + 4 snow heliports
				SPR_AIRPORT_TYPE_WATER + 68, SPR_AIRPORT_TYPE_WATER + 69, SPR_AIRPORT_TYPE_WATER + 70,
				SPR_AIRPORT_TYPE_WATER + 71, SPR_AIRPORT_TYPE_WATER + 72
			},
			{ SPR_AIRPORT_TYPE_WATER + 51, SPR_AIRPORT_TYPE_WATER + 52, SPR_AIRPORT_TYPE_WATER + 53,
				SPR_AIRPORT_TYPE_WATER + 54, SPR_AIRPORT_TYPE_WATER + 55, SPR_AIRPORT_TYPE_WATER + 56,
				SPR_AIRPORT_TYPE_WATER + 57, SPR_AIRPORT_TYPE_WATER + 58, SPR_AIRPORT_TYPE_WATER + 59,
				SPR_AIRPORT_TYPE_WATER + 60, SPR_AIRPORT_TYPE_WATER + 61, SPR_AIRPORT_TYPE_WATER + 62
			}
		},

		/* GUI sprites */
		{	SPR_AIRPORT_TYPE_WATER,
			SPR_AIRPORT_TYPE_WATER + 1,
			SPR_AIRPORT_TYPE_WATER + 2,
			SPR_AIRPORT_TYPE_WATER + 3,
			SPR_AIRPORT_TYPE_WATER + 4,
			SPR_AIRPORT_TYPE_WATER + 5,
			SPR_AIRPORT_TYPE_WATER + 6,
			SPR_AIRPORT_TYPE_WATER + 7,
			SPR_AIRPORT_TYPE_WATER + 8,
			SPR_AIRPORT_TYPE_WATER + 9,
			SPR_AIRPORT_TYPE_WATER + 10
		},

		/* cursor sprites */
		{	SPR_AIRPORT_TYPE_WATER + 11,
			SPR_AIRPORT_TYPE_WATER + 12,
			SPR_AIRPORT_TYPE_WATER + 13,
			SPR_AIRPORT_TYPE_WATER + 14,
			SPR_AIRPORT_TYPE_WATER + 15,
			SPR_AIRPORT_TYPE_WATER + 16,
			SPR_AIRPORT_TYPE_WATER + 17,
			SPR_AIRPORT_TYPE_WATER + 18,
			SPR_AIRPORT_TYPE_WATER + 19,
			SPR_AIRPORT_TYPE_WATER + 20,
			SPR_AIRPORT_TYPE_WATER + 21
		},

		/* strings */
		{
			STR_AIRTYPE_NAME_WATER,
			STR_TOOLBAR_AIRPORT_WATER_CONSTRUCTION_CAPTION,
			STR_TOOLBAR_AIRPORT_WATER_CONSTRUCTION_CAPTION,
			STR_REPLACE_AIRCRAFT_WATER_VEHICLES,
		},

		/* Offset of snow tiles */
		SPR_RAIL_SNOW_OFFSET,

		/* Compatible airtypes */
		AIRTYPES_GRAVEL | AIRTYPES_ASPHALT | AIRTYPES_WATER,

		/* fallback_airtype */
		0,

		/* cost multiplier */
		4,

		/* maintenance cost multiplier */
		4,

		/* max speed */
		35,

		/* Gravel type label. */
		AIRTYPE_LABEL_WATER,

		/* alternate labels */
		AirTypeLabelList(),

		/* map colour */
		0x0A,

		/* introduction date */
		CalTime::INVALID_DATE,

		/* airtypes required for this to be introduced */
		AIRTYPES_NONE,

		/* introduction air types */
		AIRTYPES_WATER,

		/* sort order */
		2 << 4 | 7,

		{ nullptr },
		{ nullptr },

		/* Catchment. */
		4,

		/* Max number of runways. */
		2,

		/* Min runway length in tiles. */
		5,

		/* Base noise level. */
		1,

		/* Runway noise level. */
		0,

		/* Heliport availability. */
		false,

		/* Build on water. */
		true,
	},

	/** Asphalt dark */
	{ // Main Sprites
		{
			{
				SPR_AIRPORT_TYPE_DARK + 22,
				SPR_AIRPORT_TYPE_DARK + 23,
				SPR_AIRPORT_TYPE_DARK + 24,
				SPR_AIRPORT_TYPE_DARK + 25,
				SPR_AIRPORT_TYPE_DARK + 26,
				SPR_AIRPORT_TYPE_DARK + 22,
				SPR_AIRPORT_TYPE_DARK + 22,
				SPR_AIRPORT_TYPE_DARK + 22,
				SPR_AIRPORT_TYPE_DARK + 22,
				SPR_AIRPORT_TYPE_DARK + 22,
				SPR_AIRPORT_TYPE_DARK + 22,
				SPR_AIRPORT_TYPE_DARK + 22,
				SPR_AIRPORT_TYPE_DARK + 22,
				SPR_AIRPORT_TYPE_DARK + 22,
				SPR_AIRPORT_TYPE_DARK + 22,
				SPR_AIRPORT_TYPE_DARK + 22,
				SPR_AIRPORT_TYPE_DARK + 22,
				SPR_AIRPORT_TYPE_DARK + 22,
				SPR_AIRPORT_TYPE_DARK + 22,
				SPR_AIRPORT_TYPE_DARK + 22,
			},
			{
				{
					{ SPR_AIRPORT_TYPE_DARK + 89, SPR_AIRPORT_TYPE_DARK + 90,
						SPR_AIRPORT_TYPE_ASPHALT + 91, SPR_AIRPORT_TYPE_ASPHALT+ 92
					},
					{ SPR_AIRPORT_TYPE_ASPHALT + 93, SPR_AIRPORT_TYPE_ASPHALT + 94,
						SPR_AIRPORT_TYPE_ASPHALT + 95, SPR_AIRPORT_TYPE_ASPHALT + 96
					},
					{ SPR_AIRPORT_TYPE_ASPHALT + 97, SPR_AIRPORT_TYPE_ASPHALT + 98,
						SPR_AIRPORT_TYPE_ASPHALT + 99, SPR_AIRPORT_TYPE_ASPHALT + 100
					},
					{ SPR_AIRPORT_TYPE_ASPHALT + 101, SPR_AIRPORT_TYPE_ASPHALT + 102,
						SPR_AIRPORT_TYPE_ASPHALT + 103, SPR_AIRPORT_TYPE_ASPHALT + 104
					},
					{ SPR_AIRPORT_TYPE_ASPHALT + 105, SPR_AIRPORT_TYPE_ASPHALT + 106,
						SPR_AIRPORT_TYPE_ASPHALT + 107, SPR_AIRPORT_TYPE_ASPHALT + 108
					}
				},
				{
					{ SPR_AIRPORT_TYPE_ASPHALT + 109, SPR_AIRPORT_TYPE_ASPHALT + 110,
						SPR_AIRPORT_TYPE_ASPHALT + 111, SPR_AIRPORT_TYPE_ASPHALT + 112
					},
					{ SPR_AIRPORT_TYPE_ASPHALT + 113, SPR_AIRPORT_TYPE_ASPHALT + 114,
						SPR_AIRPORT_TYPE_ASPHALT + 115, SPR_AIRPORT_TYPE_ASPHALT + 116
					},
					{ SPR_AIRPORT_TYPE_ASPHALT + 117, SPR_AIRPORT_TYPE_ASPHALT + 118,
						SPR_AIRPORT_TYPE_ASPHALT + 119, SPR_AIRPORT_TYPE_ASPHALT + 120
					},
					{ SPR_AIRPORT_TYPE_ASPHALT + 121, SPR_AIRPORT_TYPE_ASPHALT + 122,
						SPR_AIRPORT_TYPE_ASPHALT + 123, SPR_AIRPORT_TYPE_ASPHALT + 124
					},
					{ SPR_AIRPORT_TYPE_ASPHALT + 125, SPR_AIRPORT_TYPE_ASPHALT + 126,
						SPR_AIRPORT_TYPE_ASPHALT + 127, SPR_AIRPORT_TYPE_ASPHALT + 128
					}
				}
			},
			{
				{ SPR_AIRFIELD_WIND_1, SPR_AIRFIELD_WIND_2, SPR_AIRFIELD_WIND_3, SPR_AIRFIELD_WIND_4 }, // wind
				{ SPR_AIRFIELD_WIND_1, SPR_AIRFIELD_WIND_2, SPR_AIRFIELD_WIND_3, SPR_AIRFIELD_WIND_4 },
				{ SPR_AIRFIELD_WIND_1, SPR_AIRFIELD_WIND_2, SPR_AIRFIELD_WIND_3, SPR_AIRFIELD_WIND_4 },
				{ SPR_AIRFIELD_WIND_1, SPR_AIRFIELD_WIND_2, SPR_AIRFIELD_WIND_3, SPR_AIRFIELD_WIND_4 }
			},
			{ SPR_AIRPORT_RADAR_1, SPR_AIRPORT_RADAR_2, SPR_AIRPORT_RADAR_3, SPR_AIRPORT_RADAR_4, // radar
				SPR_AIRPORT_RADAR_5, SPR_AIRPORT_RADAR_6, SPR_AIRPORT_RADAR_7, SPR_AIRPORT_RADAR_8,
				SPR_AIRPORT_RADAR_9, SPR_AIRPORT_RADAR_A, SPR_AIRPORT_RADAR_B, SPR_AIRPORT_RADAR_C
			},
			{
				{ SPR_AIRPORT_TYPE_ASPHALT + 73, SPR_AIRPORT_TYPE_ASPHALT + 74, // transmitter
					SPR_AIRPORT_TYPE_ASPHALT + 75, SPR_AIRPORT_TYPE_ASPHALT + 76
				},
				{ SPR_AIRPORT_TYPE_ASPHALT + 77, SPR_AIRPORT_TYPE_ASPHALT + 78,
					SPR_AIRPORT_TYPE_ASPHALT + 79, SPR_AIRPORT_TYPE_ASPHALT + 80
				},
				{ SPR_AIRPORT_TYPE_ASPHALT + 81, SPR_AIRPORT_TYPE_ASPHALT + 82, // snowed transmitter
					SPR_AIRPORT_TYPE_ASPHALT + 83, SPR_AIRPORT_TYPE_ASPHALT + 84
				},
				{ SPR_AIRPORT_TYPE_ASPHALT + 85, SPR_AIRPORT_TYPE_ASPHALT + 86,
					SPR_AIRPORT_TYPE_ASPHALT + 87, SPR_AIRPORT_TYPE_ASPHALT + 88
				}
			},
			{ SPR_AIRPORT_TYPE_ASPHALT + 27, SPR_AIRPORT_TYPE_ASPHALT + 28, SPR_AIRPORT_TYPE_ASPHALT +29, // runways
					SPR_AIRPORT_TYPE_ASPHALT + 30, SPR_AIRPORT_TYPE_ASPHALT + 31, SPR_AIRPORT_TYPE_ASPHALT + 32,
					SPR_AIRPORT_TYPE_ASPHALT +33, SPR_AIRPORT_TYPE_ASPHALT +34, SPR_AIRPORT_TYPE_ASPHALT +35,
					SPR_AIRPORT_TYPE_ASPHALT + 36, SPR_AIRPORT_TYPE_ASPHALT + 37, SPR_AIRPORT_TYPE_ASPHALT + 38,
					SPR_AIRPORT_TYPE_ASPHALT + 39, SPR_AIRPORT_TYPE_ASPHALT + 40, SPR_AIRPORT_TYPE_ASPHALT + 41,
					SPR_AIRPORT_TYPE_ASPHALT + 42, SPR_AIRPORT_TYPE_ASPHALT + 43, SPR_AIRPORT_TYPE_ASPHALT + 44,
					SPR_AIRPORT_TYPE_ASPHALT + 45, SPR_AIRPORT_TYPE_ASPHALT + 46, SPR_AIRPORT_TYPE_ASPHALT + 47,
					SPR_AIRPORT_TYPE_ASPHALT + 48, SPR_AIRPORT_TYPE_ASPHALT + 49, SPR_AIRPORT_TYPE_ASPHALT + 50
			},
			{ SPR_AIRPORT_TYPE_ASPHALT + 63, SPR_AIRPORT_TYPE_ASPHALT + 64, // plane apron, helipad
				SPR_AIRPORT_TYPE_ASPHALT + 65, SPR_AIRPORT_TYPE_ASPHALT + 66, SPR_AIRPORT_TYPE_ASPHALT + 67, // 4 heliport rotations + 4 snow heliports
				SPR_AIRPORT_TYPE_ASPHALT + 68, SPR_AIRPORT_TYPE_ASPHALT + 69, SPR_AIRPORT_TYPE_ASPHALT + 70,
				SPR_AIRPORT_TYPE_ASPHALT + 71, SPR_AIRPORT_TYPE_ASPHALT + 72
			},
			{ SPR_AIRPORT_TYPE_ASPHALT + 51, SPR_AIRPORT_TYPE_ASPHALT + 52, SPR_AIRPORT_TYPE_ASPHALT + 53,
				SPR_AIRPORT_TYPE_ASPHALT + 54, SPR_AIRPORT_TYPE_ASPHALT + 55, SPR_AIRPORT_TYPE_ASPHALT + 56,
				SPR_AIRPORT_TYPE_ASPHALT + 57, SPR_AIRPORT_TYPE_ASPHALT + 58, SPR_AIRPORT_TYPE_ASPHALT + 59,
				SPR_AIRPORT_TYPE_ASPHALT + 60, SPR_AIRPORT_TYPE_ASPHALT + 61, SPR_AIRPORT_TYPE_ASPHALT + 62
			}
		},

		/* GUI sprites */
		{	SPR_AIRPORT_TYPE_DARK,     // add tile to airport
			SPR_AIRPORT_TYPE_DARK + 1, // build track tile
			SPR_AIRPORT_TYPE_DARK + 2, // change air type
			SPR_AIRPORT_TYPE_DARK + 3, // define runway
			SPR_AIRPORT_TYPE_DARK + 4, // apron
			SPR_AIRPORT_TYPE_DARK + 5, // helipad
			SPR_AIRPORT_TYPE_DARK + 6, // heliport
			SPR_AIRPORT_TYPE_DARK + 7, // hangar
			SPR_AIRPORT_TYPE_DARK + 8, // build predefined
			SPR_AIRPORT_TYPE_DARK + 9, // copy
			SPR_AIRPORT_TYPE_DARK + 10
		},

		/* cursor sprites */
		{	SPR_AIRPORT_TYPE_DARK + 11,
			SPR_AIRPORT_TYPE_DARK + 12,
			SPR_AIRPORT_TYPE_DARK + 13,
			SPR_AIRPORT_TYPE_DARK + 14,
			SPR_AIRPORT_TYPE_DARK + 15,
			SPR_AIRPORT_TYPE_DARK + 16,
			SPR_AIRPORT_TYPE_DARK + 17,
			SPR_AIRPORT_TYPE_DARK + 18,
			SPR_AIRPORT_TYPE_DARK + 19,
			SPR_AIRPORT_TYPE_DARK + 20,
			SPR_AIRPORT_TYPE_DARK + 21
		},

		/* strings */
		{
			STR_AIRTYPE_NAME_DARK,
			STR_TOOLBAR_AIRPORT_DARK_CONSTRUCTION_CAPTION,
			STR_TOOLBAR_AIRPORT_DARK_CONSTRUCTION_CAPTION,
			STR_REPLACE_AIRCRAFT_DARK_VEHICLES,
		},

		/* Offset of snow tiles */
		SPR_RAIL_SNOW_OFFSET,

		/* Compatible airtypes */
		AIRTYPES_YELLOW | AIRTYPES_ASPHALT,

		/* fallback_airtype */
		0,

		/* cost multiplier */
		8,

		/* maintenance cost multiplier */
		8,

		/* max speed */
		80,

		/* Gravel type label. */
		AIRTYPE_LABEL_ASPHALT_DARK,

		/* alternate labels */
		AirTypeLabelList(),

		/* map colour */
		0x0A,

		/* introduction date */
		CalTime::INVALID_DATE,

		/* airtypes required for this to be introduced */
		AIRTYPES_NONE,

		/* introduction air types */
		AIRTYPES_DARK,

		/* sort order */
		3 << 4 | 7,

		{ nullptr },
		{ nullptr },

		/* Catchment. */
		8,

		/* Max number of runways. */
		10,

		/* Min runway length in tiles. */
		5,

		/* Base noise level. */
		1,

		/* Runway noise level. */
		3,

		/* Heliport availability. */
		true,

		/* Build on water. */
		false,
	},

	/** Asphalt yellow lines */
	{ // Main Sprites
		{
			{
				SPR_AIRPORT_TYPE_YELLOW + 22,
				SPR_AIRPORT_TYPE_YELLOW + 23,
				SPR_AIRPORT_TYPE_YELLOW + 24,
				SPR_AIRPORT_TYPE_YELLOW + 25,
				SPR_AIRPORT_TYPE_YELLOW + 26,
				SPR_AIRPORT_TYPE_YELLOW + 129, // x
				SPR_AIRPORT_TYPE_YELLOW + 130, // y
				SPR_AIRPORT_TYPE_YELLOW + 131,
				SPR_AIRPORT_TYPE_YELLOW + 132,
				SPR_AIRPORT_TYPE_YELLOW + 133,
				SPR_AIRPORT_TYPE_YELLOW + 134,
				SPR_AIRPORT_TYPE_YELLOW + 135,
				SPR_AIRPORT_TYPE_YELLOW + 136,
				SPR_AIRPORT_TYPE_YELLOW + 137,
				SPR_AIRPORT_TYPE_YELLOW + 138,
				SPR_AIRPORT_TYPE_YELLOW + 139,
				SPR_AIRPORT_TYPE_YELLOW + 140,
				SPR_AIRPORT_TYPE_YELLOW + 141,
				SPR_AIRPORT_TYPE_YELLOW + 142,
				SPR_AIRPORT_TYPE_YELLOW + 143,
			},
			{
				{
					{ SPR_AIRPORT_TYPE_YELLOW + 89, SPR_AIRPORT_TYPE_YELLOW + 90,
						SPR_AIRPORT_TYPE_YELLOW + 91, SPR_AIRPORT_TYPE_YELLOW+ 92
					},
					{ SPR_AIRPORT_TYPE_YELLOW + 93, SPR_AIRPORT_TYPE_YELLOW + 94,
						SPR_AIRPORT_TYPE_YELLOW + 95, SPR_AIRPORT_TYPE_YELLOW + 96
					},
					{ SPR_AIRPORT_TYPE_YELLOW + 97, SPR_AIRPORT_TYPE_YELLOW + 98,
						SPR_AIRPORT_TYPE_YELLOW + 99, SPR_AIRPORT_TYPE_YELLOW + 100
					},
					{ SPR_AIRPORT_TYPE_YELLOW + 101, SPR_AIRPORT_TYPE_YELLOW + 102,
						SPR_AIRPORT_TYPE_YELLOW + 103, SPR_AIRPORT_TYPE_YELLOW + 104
					},
					{ SPR_AIRPORT_TYPE_YELLOW + 105, SPR_AIRPORT_TYPE_YELLOW + 106,
						SPR_AIRPORT_TYPE_YELLOW + 107, SPR_AIRPORT_TYPE_YELLOW + 108
					}
				},
				{
					{ SPR_AIRPORT_TYPE_YELLOW + 109, SPR_AIRPORT_TYPE_YELLOW + 110,
						SPR_AIRPORT_TYPE_YELLOW + 111, SPR_AIRPORT_TYPE_YELLOW + 112
					},
					{ SPR_AIRPORT_TYPE_YELLOW + 113, SPR_AIRPORT_TYPE_YELLOW + 114,
						SPR_AIRPORT_TYPE_YELLOW + 115, SPR_AIRPORT_TYPE_YELLOW + 116
					},
					{ SPR_AIRPORT_TYPE_YELLOW + 117, SPR_AIRPORT_TYPE_YELLOW + 118,
						SPR_AIRPORT_TYPE_YELLOW + 119, SPR_AIRPORT_TYPE_YELLOW + 120
					},
					{ SPR_AIRPORT_TYPE_YELLOW + 121, SPR_AIRPORT_TYPE_YELLOW + 122,
						SPR_AIRPORT_TYPE_YELLOW + 123, SPR_AIRPORT_TYPE_YELLOW + 124
					},
					{ SPR_AIRPORT_TYPE_YELLOW + 125, SPR_AIRPORT_TYPE_YELLOW + 126,
						SPR_AIRPORT_TYPE_YELLOW + 127, SPR_AIRPORT_TYPE_YELLOW + 128
					}
				}
			},
			{
				{ SPR_AIRFIELD_WIND_1, SPR_AIRFIELD_WIND_2, SPR_AIRFIELD_WIND_3, SPR_AIRFIELD_WIND_4 }, // wind
				{ SPR_AIRFIELD_WIND_1, SPR_AIRFIELD_WIND_2, SPR_AIRFIELD_WIND_3, SPR_AIRFIELD_WIND_4 },
				{ SPR_AIRFIELD_WIND_1, SPR_AIRFIELD_WIND_2, SPR_AIRFIELD_WIND_3, SPR_AIRFIELD_WIND_4 },
				{ SPR_AIRFIELD_WIND_1, SPR_AIRFIELD_WIND_2, SPR_AIRFIELD_WIND_3, SPR_AIRFIELD_WIND_4 }
			},
			{ SPR_AIRPORT_RADAR_1, SPR_AIRPORT_RADAR_2, SPR_AIRPORT_RADAR_3, SPR_AIRPORT_RADAR_4, // radar
				SPR_AIRPORT_RADAR_5, SPR_AIRPORT_RADAR_6, SPR_AIRPORT_RADAR_7, SPR_AIRPORT_RADAR_8,
				SPR_AIRPORT_RADAR_9, SPR_AIRPORT_RADAR_A, SPR_AIRPORT_RADAR_B, SPR_AIRPORT_RADAR_C
			},
			{
				{ SPR_AIRPORT_TYPE_YELLOW + 73, SPR_AIRPORT_TYPE_YELLOW + 74, // transmitter
					SPR_AIRPORT_TYPE_YELLOW + 75, SPR_AIRPORT_TYPE_YELLOW + 76
				},
				{ SPR_AIRPORT_TYPE_YELLOW + 77, SPR_AIRPORT_TYPE_YELLOW + 78,
					SPR_AIRPORT_TYPE_YELLOW + 79, SPR_AIRPORT_TYPE_YELLOW + 80
				},
				{ SPR_AIRPORT_TYPE_YELLOW + 81, SPR_AIRPORT_TYPE_YELLOW + 82, // snowed transmitter
					SPR_AIRPORT_TYPE_YELLOW + 83, SPR_AIRPORT_TYPE_YELLOW + 84
				},
				{ SPR_AIRPORT_TYPE_YELLOW + 85, SPR_AIRPORT_TYPE_YELLOW + 86,
					SPR_AIRPORT_TYPE_YELLOW + 87, SPR_AIRPORT_TYPE_YELLOW + 88
				}
			},
			{ SPR_AIRPORT_TYPE_YELLOW + 27, SPR_AIRPORT_TYPE_YELLOW + 28, SPR_AIRPORT_TYPE_YELLOW +29, // runways
					SPR_AIRPORT_TYPE_YELLOW + 30, SPR_AIRPORT_TYPE_YELLOW + 31, SPR_AIRPORT_TYPE_YELLOW + 32,
					SPR_AIRPORT_TYPE_YELLOW +33, SPR_AIRPORT_TYPE_YELLOW +34, SPR_AIRPORT_TYPE_YELLOW +35,
					SPR_AIRPORT_TYPE_YELLOW + 36, SPR_AIRPORT_TYPE_YELLOW + 37, SPR_AIRPORT_TYPE_YELLOW + 38,
					SPR_AIRPORT_TYPE_YELLOW + 39, SPR_AIRPORT_TYPE_YELLOW + 40, SPR_AIRPORT_TYPE_YELLOW + 41,
					SPR_AIRPORT_TYPE_YELLOW + 42, SPR_AIRPORT_TYPE_YELLOW + 43, SPR_AIRPORT_TYPE_YELLOW + 44,
					SPR_AIRPORT_TYPE_YELLOW + 45, SPR_AIRPORT_TYPE_YELLOW + 46, SPR_AIRPORT_TYPE_YELLOW + 47,
					SPR_AIRPORT_TYPE_YELLOW + 48, SPR_AIRPORT_TYPE_YELLOW + 49, SPR_AIRPORT_TYPE_YELLOW + 50
			},
			{ SPR_AIRPORT_TYPE_YELLOW + 63, SPR_AIRPORT_TYPE_YELLOW + 64, // plane apron, helipad
				SPR_AIRPORT_TYPE_YELLOW + 65, SPR_AIRPORT_TYPE_YELLOW + 66, SPR_AIRPORT_TYPE_YELLOW + 67, // 4 heliport rotations + 4 snow heliports
				SPR_AIRPORT_TYPE_YELLOW + 68, SPR_AIRPORT_TYPE_YELLOW + 69, SPR_AIRPORT_TYPE_YELLOW + 70,
				SPR_AIRPORT_TYPE_YELLOW + 71, SPR_AIRPORT_TYPE_YELLOW + 72
			},
			{ SPR_AIRPORT_TYPE_YELLOW + 51, SPR_AIRPORT_TYPE_YELLOW + 52, SPR_AIRPORT_TYPE_YELLOW + 53,
				SPR_AIRPORT_TYPE_YELLOW + 54, SPR_AIRPORT_TYPE_YELLOW + 55, SPR_AIRPORT_TYPE_YELLOW + 56,
				SPR_AIRPORT_TYPE_YELLOW + 57, SPR_AIRPORT_TYPE_YELLOW + 58, SPR_AIRPORT_TYPE_YELLOW + 59,
				SPR_AIRPORT_TYPE_YELLOW + 60, SPR_AIRPORT_TYPE_YELLOW + 61, SPR_AIRPORT_TYPE_YELLOW + 62
			}
		},

		/* GUI sprites */
		{	SPR_AIRPORT_TYPE_YELLOW,     // add tile to airport
			SPR_AIRPORT_TYPE_YELLOW + 1, // build track tile
			SPR_AIRPORT_TYPE_YELLOW + 2, // change air type
			SPR_AIRPORT_TYPE_YELLOW + 3, // define runway
			SPR_AIRPORT_TYPE_YELLOW + 4, // apron
			SPR_AIRPORT_TYPE_YELLOW + 5, // helipad
			SPR_AIRPORT_TYPE_YELLOW + 6, // heliport
			SPR_AIRPORT_TYPE_YELLOW + 7, // hangar
			SPR_AIRPORT_TYPE_YELLOW + 8, // build predefined
			SPR_AIRPORT_TYPE_YELLOW + 9, // copy
			SPR_AIRPORT_TYPE_YELLOW + 10
		},

		/* cursor sprites */
		{	SPR_AIRPORT_TYPE_YELLOW + 11,
			SPR_AIRPORT_TYPE_YELLOW + 12,
			SPR_AIRPORT_TYPE_YELLOW + 13,
			SPR_AIRPORT_TYPE_YELLOW + 14,
			SPR_AIRPORT_TYPE_YELLOW + 15,
			SPR_AIRPORT_TYPE_YELLOW + 16,
			SPR_AIRPORT_TYPE_YELLOW + 17,
			SPR_AIRPORT_TYPE_YELLOW + 18,
			SPR_AIRPORT_TYPE_YELLOW + 19,
			SPR_AIRPORT_TYPE_YELLOW + 20,
			SPR_AIRPORT_TYPE_YELLOW + 21
		},

		/* strings */
		{
			STR_AIRTYPE_NAME_YELLOW,
			STR_TOOLBAR_AIRPORT_YELLOW_CONSTRUCTION_CAPTION,
			STR_TOOLBAR_AIRPORT_YELLOW_CONSTRUCTION_CAPTION,
			STR_REPLACE_AIRCRAFT_YELLOW_VEHICLES,
		},

		/* Offset of snow tiles */
		SPR_RAIL_SNOW_OFFSET,

		/* Compatible airtypes */
		AIRTYPES_YELLOW | AIRTYPES_ASPHALT,

		/* fallback_airtype */
		0,

		/* cost multiplier */
		8,

		/* maintenance cost multiplier */
		8,

		/* max speed */
		80,

		/* Gravel type label. */
		AIRTYPE_LABEL_ASPHALT_YELLOW,

		/* alternate labels */
		AirTypeLabelList(),

		/* map colour */
		0x0A,

		/* introduction date */
		CalTime::INVALID_DATE,

		/* airtypes required for this to be introduced */
		AIRTYPES_NONE,

		/* introduction air types */
		AIRTYPES_YELLOW,

		/* sort order */
		4 << 4 | 7,

		{ nullptr },
		{ nullptr },

		/* Catchment. */
		8,

		/* Max number of runways. */
		10,

		/* Min runway length in tiles. */
		5,

		/* Base noise level. */
		1,

		/* Runway noise level. */
		3,

		/* Heliport availability. */
		true,

		/* Build on water. */
		false,
	},
};



#endif /* AIRTYPES_H */
